# Generated by Django 3.2.7 on 2021-09-09 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20210909_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='questionPaper',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year',
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('questionPaper', models.CharField(max_length=200, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.subject')),
            ],
        ),
    ]
