# Generated by Django 3.2.7 on 2021-09-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20210909_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='subjectName',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.subject'), max_length=200, null=True),
        ),
    ]
