# Generated by Django 3.2.7 on 2021-09-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_year_subjectname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='subjectName',
        ),
        migrations.AddField(
            model_name='year',
            name='retypeSubject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
