# Generated by Django 3.2.7 on 2021-09-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_auto_20210909_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivation',
            name='quote',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
