# Generated by Django 3.2.7 on 2021-09-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_auto_20210910_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='grade',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
